# Copyright (c) 2024 LLDPq Project
# Licensed under MIT License - see LICENSE file for details

# =============================================================================
# TOPOLOGY_CONFIG.YAML - LLDPq Expected Network Topology Definition
# =============================================================================
#
# Topology Generation Mode:
# - minimal: Uses generate_topology.py (faster, basic topology)
# - full: Uses generate_topology_full.py (comprehensive, detailed topology)
# This setting determines which script lldp-validate.py will automatically call
# If you want to use the full topology, the topology will also be displayed for devices discovered with LLDP.

topology: minimal  # [full] or [minimal]

# Topology Device Configuration
# This file defines device categorization for topology generation
# Edit this file to customize device layers and icons
# Posible icons:
# - firewall
# - switch
# - router
# - server
# - host

device_categories:
  - pattern: "inband-fw"
    layer: 1
    icon: "firewall"
    
  - pattern: "border"
    layer: 2
    icon: "switch"
    
  - pattern: "spine"
    layer: 3
    icon: "switch"
    
  - pattern: "leaf"
    layer: 4
    icon: "switch"
    
  - pattern: "oob-fw"
    layer: 5
    icon: "firewall"
    
  - pattern: "core"
    layer: 6
    icon: "switch"
    
  - pattern: "switch"
    layer: 7
    icon: "switch"

# Default category for unmatched devices
default:
  layer: 9
  icon: "server"

# Special conditional rules for devices with complex logic
special_rules:
  - pattern: "LF"
    type: "even_odd_suffix"
    even_layer: 8
    odd_layer: 7
    icon: "switch"
    description: "LF devices: even numbers -> layer 8, odd numbers -> layer 7"
